config/routes.rb
Rails.application.routes.draw do
  get 'ontology/new'
  get 'ontology/create'
  get 'ontology/update'
  get 'ontology/edit'
  get 'ontology/destroy'
  get 'ontology/index'
  get 'ontology/show'

  root 'static_pages#index'
  get 'index' => 'static_pages#index'
  get 'docs' => 'static_pages#docs'
  get 'enterprise_index' => 'static_pages#enterprise'

  get 'experiences_index' => 'experiences#index'

  resources :dashboard
  resources :place
  resources :user
  resources :experiences
  devise_for :users

  resources :place do
    collection do
      put 'show'
      post 'show'
      post 'new'
    end
  end

  resources :user do
    collection do
      put 'show'
    end 
  end

 

end

app/models/experience.rb
class Experience < ActiveRecord::Base
  belongs_to :user
  belongs_to :place
  has_many :ontologies, dependent: :destroy
  accepts_nested_attributes_for :ontologies, :allow_destroy => true
  default_scope -> { order(created_at: :desc) }
  # validates :user_id, presence: true
end

app/models/ontology.rb
class Ontology < ActiveRecord::Base
  belongs_to :experience
  default_scope -> { order(created_at: :desc) }
  # validates :experience_id, presence: true
  before_save :downcase_fields

  def downcase_fields
  	self.name.downcase!
  end
end

app/models/place.rb
class Place < ActiveRecord::Base
	has_many :experiences
	default_scope -> { order(created_at: :desc) }
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :experiences, dependent: :destroy

  # Virtual attribute for authenticating by either username or email
  # This is in addition to a real persisted field like 'username'
  attr_accessor :login

  validates :username,
  :presence => true,
  :uniqueness => {
    :case_sensitive => false
  } # etc.

  def self.find_for_database_authentication(warden_conditions)
	  conditions = warden_conditions.dup
	  if login = conditions.delete(:login)
	    where(conditions.to_hash).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
	  else
	    where(conditions.to_hash).first
	  end
	end

  def admin?
    admin
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  def hello
    render text: "hello, world!"
  end

  def after_sign_in_path_for(resource)
  	dashboard_index_path
  end

  protected

  def configure_permitted_parameters
  	devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:username, :email, :password, :password_confirmation, :remember_me) }
    devise_parameter_sanitizer.for(:sign_in) { |u| u.permit(:login, :username, :email, :password, :remember_me) }
    devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:username, :email, :password, :password_confirmation, :current_password) }
  end

end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
	before_filter :authenticate_user!

	def index
		@user = current_user
		@experience1 = Experience.first
		@experience2 = Experience.second
		@experiences = @user.experiences.paginate(page: params[:page])

	end
end

app/controllers/experiences_controller.rb
class ExperiencesController < ApplicationController

	def index
		@experiences = Experience.all
	end

	def new
		# @experience = Experience.new
		@experience = current_user.experiences.build
	end

	def create
		@experience = current_user.experiences.build(experience_params)
		if @experience.save
			flash[:success] = "Experience shared!"
			@show_place_id = Place.find(params[:experience][:place_id]).place_id 
			redirect_to :controller => 'place', :action => 'show', :place_id => @show_place_id

		else
			flash[:danger] = "Error sharing experience. Please try again." 
			render 'index'
		end
	end

	def destroy
		@experience = Experience.find(params[:id])
		@experience.destroy
		flash[:success] = "Experience deleted"
		redirect_to request.referrer || root_url
	end

	private

		def experience_params
			params.require(:experience).permit(:place_id, :content,
				:ontologies_attributes => [:experience_id, :name, :value, :_destroy])
		end

end

app/controllers/ontology_controller.rb
class OntologyController < ApplicationController
  def new
    @ontology = Ontology.new
  end

  def create
    @ontology = Ontology.new(ontology_params)
    if @ontology.save
      flash[:success] = "Ontology saved!"
      redirect_to root_url
    else
      flash[:danger] = "Error saving ontology. Please try again." 
      render 'index'
    end
  end

  def update
  end

  def edit
  end

  def destroy
  end

  def index
    @ontologies = Ontology.all
  end

  def show
  end

  private 

    def ontology_params
      params.require(:ontology).permit(:name, :value, :experience_id)
    end
end

app/controllers/place_controller.rb
class PlaceController < ApplicationController

	def index
		@places = Place.all
	end

	def new
		@place = Place.new(place_params)
		if @place.save
			flash[:success] = "Place saved to database!"
			@show_place_id = @place.place_id
			redirect_to :controller => 'place', :action => 'show', :place_id => @show_place_id
		else
			flash[:danger] = "Error saving place to database. Please try again."
			render 'index'
		end
	end

	def create
		# @place = Place.new(place_params)
		# if @place.save
		# 	flash[:success] = "Place saved to database!"
		# 	redirect_to root_url
		# else
		# 	flash[:danger] = "Error saving place to database. Please try again."
		# 	render 'index'
		# end
	end

	def show
		if user_signed_in?
			@experience = current_user.experiences.build
		end
		@place_id = params[:place_id]
		@place = Place.find_by_place_id(@place_id)
		if @place
			@experiences = @place.experiences.paginate(page: params[:page])
		else
		  @place = Place.new
		end
	end

	private

		def place_params
			params.require(:place).permit(:place_id, :place_name, :place_address)
		end

end

app/controllers/static_pages_controller.rb
	class StaticPagesController < ApplicationController
  def index
  	@experience1 = Experience.first
  	@experience2 = Experience.second
  end

  def docs
  end

  def enterprise
  	@experiences = Experience.all
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def new
  end

  def create
  end

  def update
  end

  def edit
  end

  def destroy
  end

  def index
  end

  def show
    @user_id = params[:user_id]
    @user = User.find_by_id(@user_id)
    if @user
      @experiences = @user.experiences.paginate(page: params[:page])
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

	def bootstrap_class_for flash_type
    { success: "alert-success", error: "alert-danger", alert: "alert-warning", notice: "alert-info" }[flash_type.to_sym] || flash_type.to_s
  end

  def flash_messages(opts = {})
    flash.each do |msg_type, message|
      concat(content_tag(:div, message, class: "alert #{bootstrap_class_for(msg_type)} alert-dismissible", role: 'alert') do
        concat(content_tag(:button, class: 'close', data: { dismiss: 'alert' }) do
          concat content_tag(:span, '&times;'.html_safe, 'aria-hidden' => true)
          concat content_tag(:span, 'Close', class: 'sr-only')
        end)
        concat message
      end)
    end
    nil
  end
  
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/experiences_helper.rb
module ExperiencesHelper
end

app/helpers/ontology_helper.rb
module OntologyHelper
end

app/helpers/place_helper.rb
module PlaceHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/dashboard/index.html.erb
</div>
<div class="page-heading no-bottom-margin">
  <div class="container">
    <h1><span class="glyphicon glyphicon-user"></span> Dashboard</h1>
    <h2>Welcome back</h2>
  </div>
</div>
<div id="dashboard-view" class="jumbotron no-bottom-margin">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <h2>View experiences</h2>
        <hr>
      </div>
    </div>
    <div class="row">
      <div class="col-md-8">
        <p>See how places are being reviewed and rated right now.</p>
      </div>
      <div class="col-md-4">
        <div class="panel panel-default">
          <div class="panel-heading">
            <span class="glyphicon glyphicon-comment"></span> Example experience
          </div>
          <div class="panel-body">
            <img class="full-size-image" src="/images/examples/repu-radarChartImg.png">
          </div>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-md-12">
        <hr>
        <%= link_to '<div class="btn btn-primary btn-lg pull-right">
          View all
        </div>'.html_safe, experiences_index_path %></li>
      </div>
    </div>
  </div>
</div>
<div id="ucl-widget" class="jumbotron no-bottom-margin">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <h2>Places near UCL</h2>
        <hr>
      </div>
    </div>
    <div class="row">
      <div class="col-md-4">
        <p>Check out some of the places being reviewed around UCL.</p>
      </div>
      <div class="col-md-8">
        <div class="row">
          <div class="col-md-6 text-center">
            <img class="img-circle img-thumbnail" src="/images/thumbnails/ucl-thumb.png" width="100" height="100">
            <h3>UCL</h3>
            <a href="/place/show?place_id=ChIJeTUXaS8bdkgRPhPMrn_GCNA" class="btn btn-primary">View</a>
          </div>
          <div class="col-md-6 text-center">
            <img class="img-circle img-thumbnail" src="/images/thumbnails/prc-thumb.png" width="100" height="100">
            <h3>Print Room Café</h3>
            <a href="/place/show?place_id=ChIJH7WwFC8bdkgRM-bsYAti58k" class="btn btn-primary">View</a>
          </div>
        </div>
        <div class="row">
          <div class="col-md-6 text-center">
            <img class="img-circle img-thumbnail" src="/images/thumbnails/ulu-thumb.png" width="100" height="100">
            <h3>ULU</h3>
            <a href="/place/show?place_id=ChIJo_OLHzEbdkgRdTy3kwnN-tM" class="btn btn-primary">View</a>
          </div>
          <div class="col-md-6 text-center">
            <img class="img-circle img-thumbnail" src="/images/thumbnails/waterstones-thumb.png" width="100" height="100">
            <h3>Waterstones</h3>
            <a href="/place/show?place_id=ChIJ9xRLVi4bdkgRqwdAA5ENLms" class="btn btn-primary">View</a>
          </div>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-md-12">
        <hr>
        <%= link_to '<div class="btn btn-primary btn-lg pull-right">
          View all
        </div>'.html_safe, place_index_path %></li>
      </div>
    </div>
  </div>
</div>
<div id="yield-container-body" class="container">
<div class="row">
	<div class="col-md-4">
    <h2>Profile</h2>
    <hr>
    <div class="panel panel-default">
     <div class="panel-heading">
      <span class="glyphicon glyphicon-user"></span> Profile
     </div>   
     <div class="panel-body">
      <p><strong>Username: </strong><%= @user.username %></p>
      <p><strong>Email: </strong><%= @user.email %></p>
     </div>
     <div class="panel-footer">
       <%= link_to "Edit", edit_user_registration_path, class: "btn btn-primary" %>
     </div>
    </div>
	</div>
	<div class="col-md-8">
		<% if @user.experiences.any? %>
      <h2>Experiences <span class="label label-default label-as-badge pull-right"><%= @user.experiences.count %></span></h2>
      <hr>
      <div class="experiences">
        <%= render @experiences %>
      </div>
      <%= will_paginate @experiences %>
    <% end %>
	</div>
</div>
<!-- <div class="container"> -->

app/views/experiences/_experience.html.erb
<div class="experience-wrapper col-md-6">
  <div id="experience-<%= experience.id %>" class="panel panel-default">  
    <div class="panel-heading">
      <%if defined? experience.place.place_id %>
        <span class="glyphicon glyphicon-map-marker"></span> <span class="place-id"><%= link_to experience.place.place_name, "/place/show?place_id=#{experience.place.place_id}" %></span>
      <% end %>  
    </div>
    <div class="panel-body">
      <div class="radar-chart">
        <!-- Insert d3 radar chart -->
        <div id="chart-container-<%= experience.id %>" class="chart-container"></div>
        <!-- radart chart config -->
        <script>
        RadarChart.defaultConfig.color = function() {};
        RadarChart.defaultConfig.radius = 5;
        RadarChart.defaultConfig.levels = 5;
        RadarChart.defaultConfig.maxValue = 100;
        RadarChart.defaultConfig.w = $(".chart-container").width();
        RadarChart.defaultConfig.h = $(".chart-container").width();
        RadarChart.defaultConfig.color = d3.scale.category10();
        </script>
        <!-- radar chart script -->
        <script type="text/javascript">

          var data = [
            {
              className: 'user-<%= experience.user.id %>', // optional can be used for styling
              axes: [
              ]
            }
          ];

          var drawFlag = false;

          <% experience.ontologies.each do |o| %>
            <% unless o.value.nil? or o.name.nil? %>
              var o_name = "<%= o.name %>";
              var o_value = <%= o.value %>;
              var axis = {axis: o_name, value: o_value};
              data[0].axes.push(axis);  
              drawFlag = true;
            <% end %>
          <% end %>

          if(drawFlag) {
            var chart = RadarChart.chart();
            var cfg = chart.config();
            var svg = d3.select('#chart-container-<%= experience.id %>').append('svg')
              .attr('width', cfg.w)
              .attr('height', cfg.h);
            svg.append('g').classed('single', 1).datum(data).call(chart);

            svg.append('circle')
              .attr('class', 'radar-origin')
              .attr('cx', cfg.w/2)
              .attr('cy', cfg.h/2)
              .attr('r', 10)
              .attr('fill', 'red');
          }
          
          function getRandomColor() {
              var letters = '0123456789ABCDEF'.split('');
              var color = '#';
              for (var i = 0; i < 6; i++ ) {
                  color += letters[Math.floor(Math.random() * 16)];
              }
              return color;
          }

          $(".area.user-<%= experience.user.id %>, user-<%= experience.user.id %> .circle").css('fill', getRandomColor());

        </script>
      </div>
      <div class="content"><%= experience.content %></div>
    </div>
    <div class="panel-footer">
      <div>
        <span class="glyphicon glyphicon-user"></span><span class="user"> <%= link_to experience.user.username, "/user/show?user_id=#{experience.user.id}" %></span><br>
        <span class="glyphicon glyphicon-time"></span><span class="timestamp">
           Posted <%= time_ago_in_words(experience.created_at) %> ago
        </span>
      </div>
      
      <% if user_signed_in? %>
        <% if current_user.id == experience.user.id %>
          <hr>
          <%= link_to "Delete", experience, method: :delete,
              data: { confirm: "You sure?" }, :class => "btn btn-danger" %>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/experiences/index.html.erb
</div>
<div class="page-heading">
  <div class="container">
		<h1><span class="glyphicon glyphicon-comment"></span> Experiences<span class="label label-default label-as-badge pull-right"><%= @experiences.count %></span></h1>
  </div>
</div>
<div id="yield-container-body" class="container">
<div class="experiences">
	<%= render @experiences %> 
</div>

app/views/experiences/new.html.erb
<%= render 'layouts/experience_form' %>

app/views/layouts/_experience_form.html.erb
<% if user_signed_in? %>
	<%= nested_form_for @experience, html: { multipart: true } do |f| %>
		<%= f.hidden_field :place_id, value: @place.id %>
		
		<!-- fields for ontologies -->
		<div class="ontologies-wrapper">
			<div id="ontologies">
				<h3>Ontologies</h3>
				<hr>
				<script type="text/javascript">
					var slider_iterator = 0;
				</script>
				<%= f.fields_for :ontologies, Ontology.new do |o| %>
					<div class="panel panel-default">
						<div class="panel-heading">
							<span class="glyphicon glyphicon-equalizer"></span> Specify a criteria and select score
						</div>
						<div class="panel-body">
							<div class="row">
								<div class="col-md-6">
									<%= o.label :name %><br>
									<%= o.text_field :name %>
								</div>
								<div class="col-md-6">
									<%= o.label :value %>
									<div class="ontology-slider-labels">
										<span class="glyphicon glyphicon-chevron-down"></span> Min
									  <span class="pull-right"> Max</span> 
										<span class="glyphicon glyphicon-chevron-up pull-right"></span>
									</div>		
									<%= o.number_field :value, :class => "value_ontology_slider" %>
								</div>
							</div>
							<script type="text/javascript">
								$(function() {
									var ontologySlider = $(".value_ontology_slider").last().slider({min: 0, max: 100, value: 0});
									ontologySlider.slider('setValue', 0);
									console.log("OS get value: " + ontologySlider.slider('getValue'));
								});
								
							</script>
						</div>
						<div class="panel-footer">
							<%= o.link_to_remove "<span class='glyphicon glyphicon-minus'></span> Remove".html_safe, :class => "btn btn-warning" %>
						</div>
						
					</div>
				<% end %>
				
				<%= f.link_to_add "<div id='add-ontology-button' class='btn btn-primary'><span class='glyphicon glyphicon-plus'></span> Add</div>".html_safe, :ontologies %>
				<br>
				
			</div>

		</div>
		<br>
		<h3>Comments</h3>
		<hr>
		<div class="form-group panel panel-default">
			<div class="panel-heading">
				<span class="glyphicon glyphicon-comment"></span> Leave comments</div>
			<div class="panel-body">
				<%= f.text_area :content, placeholder: "Share an experience..." %>
			</div>
		</div>
		<div class="form-group">
			<%= f.submit "Share", class: "btn btn-success" %>
		</div>
	<% end %>
<% else %>
	<p>Please <%= link_to "Log in", new_user_session_path %> to share an experience.</p>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="footer">
	<div class="container">
		<div class="row">
			<div class="col-md-4 text-center">
				<img src="/images/logo-grey.png" width="100" height="100">
				<h4>Repusition</h4>
				<!-- col 3 -->
			</div>
			<div class="col-md-4">
				<!-- col 3 -->
				<h4>Navigation</h4>
				<ul>
					<li><%= link_to "Docs", 'docs' %></li>
				</ul>
			</div>
			<div class="col-md-4">
				<!-- col 3 -->
				<h4>Resources</h4>
				<ul>
					<li><%= link_to "Ruby on Rails", 'http://rubyonrails.org/' %></li>
					<li><%= link_to "Twitter Bootstrap", 'http://getbootstrap.com/' %></li>
					<li><%= link_to "Devise", 'https://github.com/plataformatec/devise' %></li>
					<li><%= link_to "D3.js", 'http://d3js.org/' %></li>
				</ul>
			</div>
		</div>
		<hr>
		<p>&copy; 2015 Repusition</p>
	</div>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-fixed-top navbar-default">
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    
    <div class="navbar-left">
      <a href="<%= root_url %>" class="pull-left"><img src="/images/LOCATION.png" width="50" height="50"></a>
      <a href="<%= root_url %>" class="navbar-brand" style="padding-left: 0px;">Repusition</a>
      <%= render 'layouts/search' %>
    </div>
  </div>
  <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">      
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to '<span class="glyphicon glyphicon-comment"></span> Experiences'.html_safe, experiences_index_path %></li>
        <li><%= link_to '<span class="glyphicon glyphicon-map-marker"></span> Places'.html_safe, place_index_path %></li>
        <% if user_signed_in? and current_user.admin? %>
          <li><%= link_to "<span class='glyphicon glyphicon-stats'></span> Enterprise".html_safe, enterprise_index_path %></li> 
        <% end %>
        <% if user_signed_in? %>
          <li><%= link_to "<span class='glyphicon glyphicon-user'></span> #{current_user.username}".html_safe, dashboard_index_path %></li> 
        <% end %>
        <li class="dropdown">
          <% if user_signed_in? %>
            <a href=<%= dashboard_index_path %> class="dropdown-toggle" data-toggle="dropdown">Logout</span> <b class="caret"></b></a>
            <ul class="dropdown-menu">
              <li><%= link_to "Logout", destroy_user_session_path, :method => :delete %></li>                    
            </ul>
          <% else %>
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Login <b class="caret"></b></a>
            <ul class="dropdown-menu">
              <li><%= link_to "Log in", new_user_session_path %></li>
              <li><%= link_to "Sign up", new_user_registration_path %></li>
            </ul>
          <% end %>
        </li>
      </ul>       
  </div>
</nav>

app/views/layouts/_ontology_field.html.erb
<%= f.fields_for :ontologies, Ontology.new do |o| %>
	<%= o.label :name %>
	<%= o.text_field :name %>
	<%= o.label :value %>
	<%= o.number_field :value %>
<% end %>

app/views/layouts/_search.html.erb
<!-- <form class="navbar-form" role="search"> -->
    <div class="input-group pull-left">
      <div class="pull-left">
        <input id="searchTextField" type="text" class="form-control" placeholder="Search" name="q">
      </div>
      <div class="pull-left nav-search-icon">
        <i class="glyphicon search-input-label glyphicon-search pull-left glyphicon-white"></i>
      </div>
    </div>
    <!-- <div class="input-group-btn">
        <button class="btn btn-default" type="submit"><i class="glyphicon glyphicon-search"></i></button>
    </div> -->
    <!-- </div> -->
<!-- </form> -->
<script type="text/javascript">
  $(function() {
    function initialize() {
      var input = document.getElementById('searchTextField');

      var searchBox = new google.maps.places.SearchBox(input);

      // add listener to see which item is selected from the search bar
      google.maps.event.addListener(searchBox, 'places_changed', function() {
        var searchString = $("#searchTextField").val();
        var places = searchBox.getPlaces();

        function windowLocationReplace(place_id) {
          location.href = "/place/show"+"?place_id="+place_id; 
        }

        if (places.length == 1) {
          windowLocationReplace(places[0].place_id); 
        }

        if (places.length > 1) {
          $(".page-heading").empty();
          $(".page-heading").html("<div class='page-heading'><div class='container'><h1><span class='glyphicon glyphicon-search'></span> Search</h1><h2>Showing results for '"+searchString+"'</h2></div></div>");
          $("#yield-container").empty();
          $("#yield-container-body").empty();
          $("#yield-container-body").append("<table id='search-results-table' class='table table-hover'><thead><tr><th>Place name</th><th>Address</th><th>View</th></tr></thead><tbody></table>");
          for (i = 0; i < places.length; i++) {
            $('#search-results-table > tbody:last').append("<tr>"
              +"<td>"+places[i].name+"</td>"
              +"<td>"+places[i].formatted_address
              +"</td>"+"<td><input type='button' class='btn btn-primary' onclick='location.href=" + "&#34;"
              +"/place/show"+"?place_id="+places[i].place_id+"&#34;' value='View'></td></tr>");
          }
          
        }

      });
    }
    // google.maps.event.addDomListener(window, 'load', initialize);
    initialize();
  });
  
</script>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no">
  <title>RepusitionApp</title>
  <link type="text/css" rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700">
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag "radar-chart" %>
  <%= stylesheet_link_tag "style" %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
  <script type="text/javascript"
      src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCUNEP2iRg-VhOKcBUsIeg68N-buzS17oU&libraries=places&region=GB"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-backstretch/2.0.4/jquery.backstretch.min.js"></script>
</head>
<body>
	<%= render 'layouts/header' %>
	<div class="page-heading-flash no-bottom-margin">
		<div class="container">
			<%= flash_messages %>
		</div>
	</div>
	
	<div id="yield-container" class="container">
		<%= yield %>
	</div>
	
	<%= render 'layouts/footer' %>
	<!-- <div class="container"> -->
		<!-- <%= debug(params) %>-->
	<!-- </div> -->
	<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-61610631-1', 'auto');
  ga('send', 'pageview');

</script>
</body>
</html>

app/views/ontology/create.html.erb
<h1>Ontology#create</h1>
<p>Find me in app/views/ontology/create.html.erb</p>

app/views/ontology/destroy.html.erb
<h1>Ontology#destroy</h1>
<p>Find me in app/views/ontology/destroy.html.erb</p>

app/views/ontology/edit.html.erb
<h1>Ontology#edit</h1>
<p>Find me in app/views/ontology/edit.html.erb</p>

app/views/ontology/index.html.erb
<h1>Ontology#index</h1>
<p>Find me in app/views/ontology/index.html.erb</p>

app/views/ontology/new.html.erb
<h1>Ontology#new</h1>
<p>Find me in app/views/ontology/new.html.erb</p>

app/views/ontology/show.html.erb
<h1>Ontology#show</h1>
<p>Find me in app/views/ontology/show.html.erb</p>

app/views/ontology/update.html.erb
<h1>Ontology#update</h1>
<p>Find me in app/views/ontology/update.html.erb</p>

app/views/place/_blank.html.erb
<h1>Not in database</h1>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>